In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [2]:
import cactas as C
import os
import mahotas as mh
import nibabel as nib
import nrrd

In [3]:
DATAPATH='/raid/mpsych/CACTAS/DATA/ESUS'

In [4]:
images, labels = C.Helper.load_data(DATAPATH)

In [5]:
TS_PATH='TS'

In [6]:
combined = []

for subfolder in os.listdir(TS_PATH):
    subfolder_path = os.path.join(TS_PATH, subfolder)

    if os.path.isdir(subfolder_path):
        left_image_path = os.path.join(subfolder_path, 'common_carotid_artery_left.nii.gz')
        right_image_path = os.path.join(subfolder_path, 'common_carotid_artery_right.nii.gz')

        if os.path.exists(left_image_path) and os.path.exists(right_image_path):
            left_image = nib.load(left_image_path).get_fdata()
            right_image = nib.load(right_image_path).get_fdata()
            
            left_bbox = mh.bbox(left_image)
            right_bbox = mh.bbox(right_image)
            
            if  np.all(right_bbox == 0):
                right_bbox = [146, 0, 108, 0, 0, 0]

            carotid_artery_seg = [min(left_bbox[0],right_bbox[0]), max(left_bbox[1],right_bbox[1]),min(left_bbox[2],right_bbox[2]), max(left_bbox[3],right_bbox[3]),min(left_bbox[4],right_bbox[4]), max(left_bbox[5],right_bbox[5])]
            combined.append(carotid_artery_seg)

combined = np.array(combined)

In [7]:
len(combined)

70

In [8]:
combined

array([[213, 324, 242, 291,  30, 105],
       [181, 260, 258, 321,  25,  79],
       [205, 344, 212, 266,  21,  72],
       [206, 318, 220, 289,  31,  89],
       [187, 312, 221, 280,  31,  95],
       [207, 350, 252, 343,  28,  78],
       [186, 299, 205, 254,  29,  94],
       [212, 345, 190, 254,  31,  95],
       [196, 327, 251, 305,  27,  92],
       [224, 328, 216, 281,  27, 105],
       [207, 318, 268, 328,  34,  91],
       [208, 304, 216, 270,  33,  84],
       [186, 301, 197, 247,  32, 102],
       [196, 294, 245, 287,  23,  78],
       [203, 303, 217, 254,  39, 106],
       [237, 361, 165, 223,   9,  80],
       [146, 328, 108, 255,   0,  42],
       [208, 326, 203, 257,  24,  83],
       [181, 312, 260, 322,  35,  87],
       [152, 320, 108, 200,  35,  93],
       [198, 301, 283, 325,  45, 108],
       [195, 278, 224, 264,  33,  92],
       [233, 330, 243, 268,  34,  76],
       [199, 299, 158, 216,  18,  79],
       [186, 297, 252, 309,  34,  87],
       [185, 327, 248, 30

In [9]:
ts_id = []
for subfolder in os.listdir(TS_PATH):
    ts_id +=[int(subfolder)]

In [10]:
ts_id

[62,
 15,
 86,
 27,
 50,
 95,
 71,
 49,
 39,
 33,
 92,
 57,
 9,
 12,
 65,
 18,
 16,
 61,
 53,
 24,
 7,
 72,
 96,
 40,
 47,
 75,
 91,
 29,
 23,
 82,
 88,
 66,
 11,
 21,
 2,
 64,
 13,
 32,
 45,
 77,
 93,
 94,
 42,
 35,
 48,
 69,
 87,
 14,
 63,
 5,
 51,
 26,
 55,
 22,
 10,
 83,
 46,
 31,
 90,
 97,
 79,
 73,
 36,
 41,
 60,
 17,
 84,
 25,
 52,
 6]

In [11]:
ids=[]
for f in labels:
    if f.endswith('b.seg.nrrd'):
        current_id = f.split('.')[0]
        ids += [int(current_id)]

In [12]:
ids

[93,
 63,
 33,
 51,
 50,
 82,
 97,
 79,
 73,
 83,
 96,
 31,
 6,
 49,
 25,
 55,
 60,
 16,
 35,
 18,
 40,
 86,
 39,
 32,
 53,
 10,
 29,
 95,
 71,
 45,
 36,
 62,
 90,
 84,
 14,
 24,
 65,
 92,
 13,
 27,
 42,
 91,
 41,
 23,
 15,
 48,
 22,
 9,
 11,
 52,
 72,
 17,
 88,
 21,
 64,
 66,
 77,
 47,
 2,
 57,
 46,
 7,
 87,
 69,
 94,
 12,
 26,
 61,
 75,
 5]

In [13]:
seg_list=[]
for i in range(len(ids)):
    data, header = nrrd.read(DATAPATH + "/" + labels[i])
    segment = mh.bbox(data)
    seg_list.append(segment)
seg_list=np.array(seg_list)

In [14]:
len(seg_list)

70

In [15]:
seg_list = np.array(seg_list)

In [16]:
seg_list

array([[205, 210, 272, 277,  73,  76],
       [197, 299, 216, 238, 115, 124],
       [234, 239, 220, 225, 106, 112],
       [226, 319, 237, 262, 202, 238],
       [168, 331, 232, 259, 109, 116],
       [167, 323, 260, 297,  92, 105],
       [313, 338, 206, 223,  85,  99],
       [197, 329, 217, 238, 121, 130],
       [321, 336, 255, 269, 115, 122],
       [188, 303, 225, 235, 112, 130],
       [216, 349, 243, 262,  86, 104],
       [202, 324, 260, 304,  93, 118],
       [183, 296, 223, 249, 113, 131],
       [184, 336, 198, 236, 101, 118],
       [201, 359, 251, 278,  86, 103],
       [180, 184, 267, 272, 165, 169],
       [323, 330, 264, 269,  88,  91],
       [190, 331, 215, 275,  83, 106],
       [218, 340, 224, 238, 114, 118],
       [217, 352, 180, 213,  85, 105],
       [192, 305, 157, 180,  81,  86],
       [205, 342, 227, 251,  93, 100],
       [181, 333, 253, 268, 104, 110],
       [282, 294, 242, 251, 106, 115],
       [307, 314, 247, 254, 105, 108],
       [327, 341, 271, 28

In [17]:
combined[4]

array([187, 312, 221, 280,  31,  95])

In [18]:
seg_list[4]

array([168, 331, 232, 259, 109, 116])

In [19]:
min(combined[4][0],seg_list[4][0]), max(combined[4][1],seg_list[4][1]),min(combined[4][2],seg_list[4][2]),max(combined[4][3],seg_list[4][3]),min(combined[4][4],seg_list[4][4]),max(combined[4][5],seg_list[4][5])

(168, 331, 221, 280, 31, 116)

In [20]:
331-168, 280-221, 116-31

(163, 59, 85)

In [21]:
match=[]
for i in range(len(ids)):
    for j in range(len(ids)):
        if ts_id[i] == ids[j]:
            print(i, j, ts_id[i], ids[j])
            match.append((i,j))
            if len(match) == 70:
                break

0 31 62 62
1 44 15 15
2 21 86 86
3 39 27 27
4 4 50 50
5 27 95 95
6 28 71 71
7 13 49 49
8 22 39 39
9 2 33 33
10 37 92 92
11 59 57 57
12 47 9 9
13 65 12 12
14 36 65 65
15 19 18 18
16 17 16 16
17 67 61 61
18 24 53 53
19 35 24 24
20 61 7 7
21 50 72 72
22 10 96 96
23 20 40 40
24 57 47 47
25 68 75 75
26 41 91 91
27 26 29 29
28 43 23 23
29 5 82 82
30 52 88 88
31 55 66 66
32 48 11 11
33 53 21 21
34 58 2 2
35 54 64 64
36 38 13 13
37 23 32 32
38 29 45 45
39 56 77 77
40 0 93 93
41 64 94 94
42 40 42 42
43 18 35 35
44 45 48 48
45 63 69 69
46 62 87 87
47 34 14 14
48 1 63 63
49 69 5 5
50 3 51 51
51 66 26 26
52 15 55 55
53 46 22 22
54 25 10 10
55 9 83 83
56 60 46 46
57 11 31 31
58 32 90 90
59 6 97 97
60 7 79 79
61 8 73 73
62 30 36 36
63 42 41 41
64 16 60 60
65 51 17 17
66 33 84 84
67 14 25 25
68 49 52 52
69 12 6 6


In [22]:
match

[(0, 31),
 (1, 44),
 (2, 21),
 (3, 39),
 (4, 4),
 (5, 27),
 (6, 28),
 (7, 13),
 (8, 22),
 (9, 2),
 (10, 37),
 (11, 59),
 (12, 47),
 (13, 65),
 (14, 36),
 (15, 19),
 (16, 17),
 (17, 67),
 (18, 24),
 (19, 35),
 (20, 61),
 (21, 50),
 (22, 10),
 (23, 20),
 (24, 57),
 (25, 68),
 (26, 41),
 (27, 26),
 (28, 43),
 (29, 5),
 (30, 52),
 (31, 55),
 (32, 48),
 (33, 53),
 (34, 58),
 (35, 54),
 (36, 38),
 (37, 23),
 (38, 29),
 (39, 56),
 (40, 0),
 (41, 64),
 (42, 40),
 (43, 18),
 (44, 45),
 (45, 63),
 (46, 62),
 (47, 34),
 (48, 1),
 (49, 69),
 (50, 3),
 (51, 66),
 (52, 15),
 (53, 46),
 (54, 25),
 (55, 9),
 (56, 60),
 (57, 11),
 (58, 32),
 (59, 6),
 (60, 7),
 (61, 8),
 (62, 30),
 (63, 42),
 (64, 16),
 (65, 51),
 (66, 33),
 (67, 14),
 (68, 49),
 (69, 12)]

In [23]:
match[0]

(0, 31)

In [24]:
match[0][0]

0

In [25]:
match[0][1]

31

In [26]:
combined[match[0][0]]

array([213, 324, 242, 291,  30, 105])

In [27]:
seg_list[match[0][1]]

array([221, 345, 233, 251, 109, 123])

In [28]:
min(combined[match[0][0]][0],seg_list[match[0][1]][0])

213

In [29]:
max(combined[match[0][0]][1],seg_list[match[0][1]][1])

345

In [30]:
min(combined[match[0][0]][2],seg_list[match[0][1]][2])

233

In [31]:
max(combined[match[0][0]][3],seg_list[match[0][1]][3])

291

In [32]:
min(combined[match[0][0]][4],seg_list[match[0][1]][4])

30

In [33]:
max(combined[match[0][0]][5],seg_list[match[0][1]][5])

123

In [34]:
345-213, 291-233, 123-30

(132, 58, 93)

In [35]:
differences=[min(combined[match[0][0]][0],seg_list[match[0][1]][0]),max(combined[match[0][0]][1],seg_list[match[0][1]][1]),min(combined[match[0][0]][2],seg_list[match[0][1]][2]),max(combined[match[0][0]][3],seg_list[match[0][1]][3]),min(combined[match[0][0]][4],seg_list[match[0][1]][4]),max(combined[match[0][0]][5],seg_list[match[0][1]][5])]

In [36]:
differences

[213, 345, 233, 291, 30, 123]

In [37]:
xy=[differences[3]-differences[2], differences[1]-differences[0]]

In [38]:
xy

[58, 132]

In [40]:
diff=[]
xy_diff=[]
for i in range(len(ids)):
    diff.append([min(combined[match[i][0]][0],seg_list[match[i][1]][0]),max(combined[match[i][0]][1],seg_list[match[i][1]][1]),min(combined[match[i][0]][2],seg_list[match[i][1]][2]),max(combined[match[i][0]][3],seg_list[match[i][1]][3]),min(combined[match[i][0]][4],seg_list[match[i][1]][4]),max(combined[match[i][0]][5],seg_list[match[i][1]][5])])
    xy_diff.append([diff[i][3]-diff[i][2], diff[i][1]-diff[i][0]])
     

In [41]:
diff

[[213, 345, 233, 291, 30, 123],
 [181, 291, 258, 321, 25, 110],
 [205, 344, 212, 266, 21, 100],
 [193, 318, 220, 289, 31, 121],
 [168, 331, 221, 280, 31, 116],
 [207, 350, 252, 343, 28, 87],
 [176, 321, 205, 254, 29, 130],
 [184, 345, 190, 254, 31, 118],
 [181, 333, 251, 305, 27, 110],
 [224, 328, 216, 281, 27, 112],
 [202, 318, 238, 328, 34, 109],
 [190, 311, 216, 290, 33, 108],
 [186, 317, 186, 247, 32, 118],
 [196, 335, 244, 287, 23, 100],
 [190, 303, 217, 256, 39, 207],
 [217, 361, 165, 223, 9, 105],
 [146, 331, 108, 275, 0, 106],
 [208, 341, 201, 257, 24, 106],
 [181, 314, 247, 322, 35, 108],
 [135, 324, 108, 246, 35, 105],
 [198, 310, 255, 325, 45, 133],
 [195, 312, 224, 264, 33, 105],
 [216, 349, 243, 268, 34, 104],
 [192, 305, 157, 216, 18, 86],
 [186, 297, 240, 309, 34, 96],
 [172, 355, 248, 309, 26, 105],
 [159, 323, 257, 340, 17, 99],
 [192, 327, 203, 289, 33, 102],
 [151, 299, 195, 299, 19, 83],
 [167, 323, 232, 297, 28, 105],
 [249, 396, 263, 356, 0, 79],
 [184, 294, 187, 

In [42]:
len(diff)

70

In [43]:
xy_diff

[[58, 132],
 [63, 110],
 [54, 139],
 [69, 125],
 [59, 163],
 [91, 143],
 [49, 145],
 [64, 161],
 [54, 152],
 [65, 104],
 [90, 116],
 [74, 121],
 [61, 131],
 [43, 139],
 [39, 113],
 [58, 144],
 [167, 185],
 [56, 133],
 [75, 133],
 [138, 189],
 [70, 112],
 [40, 117],
 [25, 133],
 [59, 113],
 [69, 111],
 [61, 183],
 [83, 164],
 [86, 135],
 [104, 148],
 [65, 156],
 [93, 147],
 [45, 110],
 [66, 116],
 [65, 153],
 [61, 121],
 [50, 90],
 [49, 114],
 [55, 131],
 [61, 110],
 [71, 110],
 [43, 96],
 [34, 110],
 [105, 166],
 [68, 129],
 [52, 121],
 [58, 100],
 [38, 103],
 [55, 132],
 [70, 106],
 [77, 120],
 [67, 97],
 [54, 137],
 [88, 118],
 [43, 127],
 [48, 148],
 [49, 126],
 [62, 92],
 [61, 122],
 [96, 188],
 [62, 103],
 [58, 133],
 [54, 132],
 [61, 138],
 [53, 133],
 [68, 138],
 [48, 83],
 [41, 82],
 [70, 158],
 [67, 109],
 [38, 113]]

In [44]:
len(xy_diff)

70